# Generated by Django 2.2.4 on 2019-09-10 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='status',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='number',
            new_name='x_number',
        ),
        migrations.RemoveField(
            model_name='game',
            name='session_name',
        ),
    ]
